//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _LLFENG_H_
#define _LLFENG_H_

#include <TinyCLR_Interop.h>
struct Library_LLFeng_LLFeng_TFT
{
    TINYCLR_NATIVE_DECLARE(showinfo___STATIC__VOID__STRING);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_LLFeng;

#endif  //_LLFENG_H_
