//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "LLFeng.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_LLFeng_LLFeng_TFT::showinfo___STATIC__VOID__STRING,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_LLFeng =
{
    "LLFeng", 
    0x597E56C6,
    method_lookup
};

