//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _NXP_SPOT_INTEROP_H_
#define _NXP_SPOT_INTEROP_H_

#include <TinyCLR_Interop.h>
struct Library_NXP_SPOT_Interop_NXP_SPOT_Interop_ReadAndWriteMemory
{
    TINYCLR_NATIVE_DECLARE(Read___STATIC__U4__U4);
    TINYCLR_NATIVE_DECLARE(Wirte___STATIC__VOID__U4__U4);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NXP_SPOT_Interop;

#endif  //_NXP_SPOT_INTEROP_H_
