//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "NXP_SPOT_Interop.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_NXP_SPOT_Interop_NXP_SPOT_Interop_ReadAndWriteMemory::Read___STATIC__U4__U4,
    Library_NXP_SPOT_Interop_NXP_SPOT_Interop_ReadAndWriteMemory::Wirte___STATIC__VOID__U4__U4,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_NXP_SPOT_Interop =
{
    "NXP.SPOT.Interop", 
    0xEB296775,
    method_lookup
};

