//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _LLFENG_H_
#define _LLFENG_H_

#include <TinyCLR_Interop.h>
struct Library_LLFeng_LLFeng_Beep
{
    TINYCLR_NATIVE_DECLARE(beepon___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(beepoff___STATIC__VOID);

    //--//

};

struct Library_LLFeng_LLFeng_TPAD
{
    TINYCLR_NATIVE_DECLARE(TPAD_Reset___STATIC__VOID);
    TINYCLR_NATIVE_DECLARE(TPAD_Get_Val___STATIC__U2);
    TINYCLR_NATIVE_DECLARE(TPAD_Get_MaxVal___STATIC__U2__U4);
    TINYCLR_NATIVE_DECLARE(TPAD_Init___STATIC__U2__U4);
    TINYCLR_NATIVE_DECLARE(TPAD_Scan___STATIC__U2__U4);
    TINYCLR_NATIVE_DECLARE(TIM5_CH2_Cap_Init___STATIC__VOID__U2__U2);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_LLFeng;

#endif  //_LLFENG_H_
