//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "LLFeng.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    Library_LLFeng_LLFeng_Beep::beepon___STATIC__VOID,
    Library_LLFeng_LLFeng_Beep::beepoff___STATIC__VOID,
    NULL,
    Library_LLFeng_LLFeng_TPAD::TPAD_Reset___STATIC__VOID,
    Library_LLFeng_LLFeng_TPAD::TPAD_Get_Val___STATIC__U2,
    Library_LLFeng_LLFeng_TPAD::TPAD_Get_MaxVal___STATIC__U2__U4,
    Library_LLFeng_LLFeng_TPAD::TPAD_Init___STATIC__U2__U4,
    Library_LLFeng_LLFeng_TPAD::TPAD_Scan___STATIC__U2__U4,
    Library_LLFeng_LLFeng_TPAD::TIM5_CH2_Cap_Init___STATIC__VOID__U2__U2,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_LLFeng =
{
    "LLFeng", 
    0xCDDD2BCE,
    method_lookup
};

